# Generated by Django 6.0 on 2025-12-29 22:11

import api.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StructureC04',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idType', models.CharField(max_length=1)),
                ('idNumber', models.CharField(max_length=20)),
                ('operationNumber', models.CharField(max_length=50)),
                ('assetCode', models.CharField(max_length=50)),
                ('assetType', models.CharField(max_length=10)),
                ('issuer', models.CharField(max_length=100)),
                ('issueDate', models.DateField()),
                ('maturityDate', models.DateField()),
                ('nominalValue', models.DecimalField(decimal_places=2, max_digits=15, validators=[api.utils.validators.validate_decimal_precision])),
                ('accountingDate', models.DateField()),
                ('bookValue', models.DecimalField(decimal_places=2, max_digits=15, validators=[api.utils.validators.validate_decimal_precision])),
                ('lastAppraisalValue', models.DecimalField(decimal_places=2, max_digits=15, validators=[api.utils.validators.validate_decimal_precision])),
                ('provisionValue', models.DecimalField(decimal_places=2, max_digits=15, validators=[api.utils.validators.validate_decimal_precision])),
                ('realizationDate', models.DateField(blank=True, null=True)),
                ('realizationValue', models.DecimalField(decimal_places=2, max_digits=15, validators=[api.utils.validators.validate_decimal_precision])),
                ('recordStatus', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'c04',
            },
        ),
        migrations.CreateModel(
            name='StructureI01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrumentNumber', models.CharField(max_length=50)),
                ('issuerIdType', models.CharField(max_length=1)),
                ('issuerId', models.CharField(max_length=20)),
                ('issueDate', models.DateField()),
                ('purchaseDate', models.DateField()),
                ('instrumentType', models.CharField(max_length=10)),
                ('issuerCountry', models.CharField(max_length=3)),
                ('nominalValueUsd', models.DecimalField(decimal_places=2, max_digits=15, validators=[api.utils.validators.validate_decimal_precision])),
                ('purchaseValueUsd', models.DecimalField(decimal_places=2, max_digits=15, validators=[api.utils.validators.validate_decimal_precision])),
                ('couponPaymentPeriodDays', models.IntegerField()),
                ('issuerClassification', models.CharField(max_length=2)),
                ('issuerType', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'i01',
            },
        ),
        migrations.CreateModel(
            name='StructureI02',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrumentNumber', models.CharField(max_length=50)),
                ('issuerIdType', models.CharField(max_length=1)),
                ('issuerId', models.CharField(max_length=20)),
                ('issueDate', models.DateField()),
                ('purchaseDate', models.DateField()),
                ('maturityDate', models.DateField()),
                ('riskRating', models.CharField(max_length=10)),
                ('ratingAgency', models.CharField(max_length=50)),
                ('lastRatingDate', models.DateField()),
                ('accountCode', models.CharField(max_length=20)),
                ('bookValueUsd', models.DecimalField(decimal_places=2, max_digits=15, validators=[api.utils.validators.validate_decimal_precision])),
                ('instrumentStatus', models.CharField(max_length=5)),
                ('nominalInterestRate', models.DecimalField(decimal_places=2, max_digits=5, validators=[api.utils.validators.validate_decimal_precision])),
                ('accruedInterestUsd', models.DecimalField(decimal_places=2, max_digits=15, validators=[api.utils.validators.validate_decimal_precision])),
                ('regulatoryRiskRating', models.CharField(max_length=5)),
                ('provisionAmountUsd', models.DecimalField(decimal_places=2, max_digits=15, validators=[api.utils.validators.validate_decimal_precision])),
            ],
            options={
                'db_table': 'i02',
            },
        ),
    ]
